services:
  - type: web
    name: vocab-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_interface:app --timeout 120 --workers 1 --threads 4 & python scheduler.py
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: WORDS_PER_DAY
        value: "2"
      - key: SCHEDULE_TIME
        value: "09:00"
